---
- name: Create a VM on the vcenter VEGA 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    - name: deploy a vm with name is vm-win-ansible, datastore is vega01 and template WIN2019 and in folder Crif-PoC, networks is dhcp
      community.vmware.vmware_guest:
        folder: /Crif-PoC

        name: vm-win-ansible
        state: poweredon
        template: WIN2019
        customization:
          existing_vm: false
          dns_servers:
            - 1.1.1.1
            - 8.8.8.8
          dns_suffix:
            - hx-devops.com.ch
        networks:
          - name: VM-Network
            connected: true
            start_connected: true
        wait_for_ip_address: true
      delegate_to: localhost
    - name: customize cpu, memory and disk
      community.vmware.vmware_guest:
        folder: /Crif-PoC
        name: vm-win-ansible
  
        template: WIN2019
        disk:
          - size_gb: 120
            type: thin

        hardware:
          memory_mb: 1024
          num_cpus: 2
          scsi: paravirtual
      delegate_to: localhost
    
    - name: turn on the vm
      community.vmware.vmware_guest:
        folder: /Crif-PoC
        name: vm-win-ansible
        state: powerup
      delegate_to: localhost
    

