---
- name: Create a VM on the vcenter VEGA 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    - name: deploy a vm with name is vm-centos-ansible, datastore is vega01 and template CentOS7 and in folder Crif-PoC, networks is dhcp
      community.vmware.vmware_guest:
        name: vm-centos-ansible

        datacenter: VEGA
        folder: /CRIF-PoC
        datastore: vega01
        state: poweredon
        template: CentOS7
        customization:
          existing_vm: false
          dns_servers:
            - 1.1.1.1
            - 8.8.8.8
          dns_suffix:
            - vega.local
        disk:
            - size_gb: 120
              type: thin

        hardware:
          memory_mb: 1024
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: vegavm15
            connected: true
            start_connected: true
        wait_for_ip_address: true
      delegate_to: localhost

    - name: perform a vmotion if the vm is in host numeber 1
      community.vmware.vmware_vmotion:
 
        vm_name: vm-centos-ansible
        destination_host: vegaesx01.vega.local
      delegate_to: localhost


