---
- name: Create a VM on the vcenter VEGA 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    - name: deploy a vm with name is vm-win-ansible, datastore is vega01 and template WIN2019 and in folder Crif-PoC, networks is dhcp
      community.vmware.vmware_guest:
        name: vm-centos-ansible

        datacenter: VEGA
        folder: /CRIF-PoC
        datastore: vega01
        state: poweredon
        template: CentOS7
        customization:
          existing_vm: false
          dns_servers:
            - 1.1.1.1
            - 8.8.8.8
          dns_suffix:
            - hx-devops.com.ch
        networks:
          - name: vegavm15
            connected: true
            start_connected: true
        wait_for_ip_address: true
      delegate_to: localhost


