---
- name: VM running host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    - name: Look up the VM called Winsozz_test in the inventory
      register: search_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - Winsozz_test
    
    - name: Collect information about a specific VM
      vmware.vmware_rest.vcenter_vm_info:
        vm: '{{ search_result.value[0].vm }}'
      register: Winsozz_test_info
    
    - name: Get guest identity information
      vmware.vmware_rest.vcenter_vm_guest_identity_info:
        vm: '{{ Winsozz_test_info.id }}'
      register: _result

    - name: Gather one specific VM
      community.vmware.vmware_vm_info:
        vm_name: 'vm_name_as_per_vcenter'
      delegate_to: localhost
      register: vm_info
