---
- name: VM running host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Gather information about the VM
      community.vmware.vmware_vm_info:
        validate_certs: no  # Set to 'yes' if you want to validate SSL certificates

      # Filter the VM information to find Winsozz_test
      register: vm_info

    - name: Check VM name in the result variable
      with_items: "{{ vm_info.virtual_machines }}"
      when: item.guest_name == "Winsozz_test"
      register: vm_info_guest


    - name: Display ESXi host information
      debug:
        msg: "{{ vm_info_guest.esxi_hostname }}"
